[default.databases]
oidc_db = { url = "mysql://oidc:oidc@127.0.0.1/oidc" }

[debug]
address = "127.0.0.1"
port = 8000
log_level = "normal"

[release]
address = "0.0.0.0"
port = 80
log_level = "normal"
